// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8cDsnPMKz5xb_PJyhMvpUqiFd7Pel4mI',
    appId: '1:45778247575:web:342efe652aa88bc59baed2',
    messagingSenderId: '45778247575',
    projectId: 'myappchat-725ad',
    authDomain: 'myappchat-725ad.firebaseapp.com',
    storageBucket: 'myappchat-725ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWXLagxC_9Vd9wq_KOsa5t0uCn7xJDm_k',
    appId: '1:45778247575:android:d2989ddc6cc06a999baed2',
    messagingSenderId: '45778247575',
    projectId: 'myappchat-725ad',
    storageBucket: 'myappchat-725ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw8OX8KQ0mIGKT0HY_lqD2aVxm2VbDptg',
    appId: '1:45778247575:ios:638ed503e062a25b9baed2',
    messagingSenderId: '45778247575',
    projectId: 'myappchat-725ad',
    storageBucket: 'myappchat-725ad.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );
}
